version: 2

models:
  - name: re_data_base_metrics
    description: >
      Internal table containing most of described metrics. To really access
      metrics it's usually better to use view for specific metric.
    
    columns:
      - name: table_name
        tests:
          - not_null
      
      - name: column_name
        description: >
          Column name which metric is about, it can be empty string: '' in case of table level metric
        tests:
          - not_null

      - name: metric
        tests:
          - not_null
      
      - name: value
        description: >
          Value of a metric, it *can* be null in case of no new records existing in given time frame.

      - name: time_window_start
        tests:
          - not_null

      - name: time_window_end
        tests:
          - not_null
      
      - name: computed_on
        tests:
          - not_null